name: dart_shelf_server
description: Server using Shelf for Dart.
publish_to: 'none'
version: 1.0.0
repository: https://github.com/localtoast3000/dart_shelf_server.git

environment:
  sdk: ^3.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
